### ISSUE TITLE
Adt package fail on IOS version.

### ISSUE THREAD

**Issue by lovewqcm520** [digicrafts/Rating-ANE#1]
Use adt command package ios version in air 3.9 throw error:

ld: file not found: %ADT_ENV_VAR_67%
Compilation failed while executing : ld64

Android version ane works fine.

**Comment by tsangwailam** [comment]
Thanks. will check that soon.

**Comment by cdouglasnet** [comment]
I have had a similar error when building for iOS:
Id: file not found: %ADT_ENV_VAR_65%
Compilation failed while executing : ld64

I was compiling on a Win 7 PC / Flash Pro CC 2014
I was able to build for iOS with no problems on my Mac.

Thanks for Sharing This Great ANE!

**Comment by tsangwailam** [comment]
@cdouglasnet Are your windows machine can connect to internet when development?
