### ISSUE TITLE
Error - extension context doesnt not have a method with name....

### ISSUE THREAD

**Issue by harshhsrah** [digicrafts/Rating-ANE#3]
I am getting this error all the time
Error #3500: The extension context does not have a method with the name applicationLaunched
OR
Error #3500: The extension context does not have a method with the name setProperty.

Can someone indicate how to use the extension with flash CS6, AIR 13

**Comment by tsangwailam** [comment]
Are you using in simulator?

**Comment by harshhsrah** [comment]
I am compiling the swf file in Flash, when I am getting the error. Once the swf is complied, it is packaged with AIR as .apk or .ipa using command line
