### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by leossmith** [digicrafts/Rating-ANE#4]
I get the following error while compiling with air15

ld: file not found: %ADT_ENV_VAR_67%
Compilation failed while executing : ld64

Windows 8.1 64bit
Flash Builder 4.7
Updated ld64 to latest
Internet Connection: Active

any ideas?

**Comment by tsangwailam** [comment]
This happen sometime only on window machine, don't know if it is problem of different ld version. To ensure to fix this, you need to build the ANE in your machine.

BTW, what java version are you using? try a newer one may be help.

**Comment by leossmith** [comment]
i am using jdk 1.8.25. i will try to compile in a mac to see if this will work.

**Comment by tsangwailam** [comment]
it's compiled with older Air SDK. It may lead to the problem. I will recompile it when the AIR 16 is ready which included the 64bit support.

**Comment by leossmith** [comment]
any update on this one? i will be soon pushing an update on my apps with air 16 and i would love to include your ane :)

**Comment by tsangwailam** [comment]
We are updating it to support 64bit. Will be complete about this week.

**Comment by leossmith** [comment]
awesome :) thanx for the update :+1:

**Comment by tsangwailam** [comment]
Could you try if the new commit have any problem.

**Comment by leossmith** [comment]
i will try on a clear project as i got an error today due to using 3 other ane on our project which were not updated to air 16. i will keep you posted.

**Comment by leossmith** [comment]
it compiled without any errors which is nice :) although i configured it to show me the rating dialog after 0.5 day it didn't work. am i doing something wrong? in any case the compiler error is fixed :+1:

**Comment by tsangwailam** [comment]
The day should not work with floating point. Need to have integer.
