### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stepan-beresnev** [digicrafts/Rating-ANE#9]
The project includes LICENSE file with GPL license, and Rating.as has BSD license text.
Which one is correct one? Can you please remove wrong one?

**Comment by tsangwailam** [comment]
Thanks. We will remove the license text in as file.

**Comment by stepan-beresnev** [comment]
So are you going to remove BSD license from .as file and leave GPL? I think, a lot of people won't be able to use your ANE after that. Or will you move the text from .as to LICENSE file? Thanks.

**Comment by tsangwailam** [comment]
OK. It is more appropriate for just simple delete the License file.
